import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { Navigation, Pagination, Scrollbar, A11y, Autoplay } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import Box from "@mui/material/Box";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import { Typography } from "@mui/material";
import { Grid } from "@mui/material";
import { Paper } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>sirokuro.site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>
      {/* <main className={styles.main}> */}
      {/* <h1 className={styles.title}>Welcome to sirokuro (CONCEPT) .site</h1> */}
      <main>
        <Swiper
          modules={[Navigation, Pagination, Scrollbar, A11y, Autoplay]}
          spaceBetween={50}
          slidesPerView={1}
          navigation
          pagination={{ clickable: true }}
          scrollbar={{ draggable: true }}
          onSwiper={(swiper) => console.log(swiper)}
          onSlideChange={() => console.log("slide change")}
          // autoplay={{
          //   delay: 5000,
          //   disableOnInteraction: true,
          //   waitForTransition: false,
          // }}
          loop={true}
          // loopAdditionalSlides={1}
          speed={500}
        >
          {/* {items.map((banneritem, index) => { */}
          <SwiperSlide>
            <h1 className={styles.title}>
              Welcome to sirokuro (CONCEPT) .site
            </h1>
          </SwiperSlide>
          <SwiperSlide>
            <Box
              sx={{
                height: 25,
                backgroundColor: "black",
              }}
            >
              <h3 className={styles.textwhite}>まずはじめに</h3>
            </Box>
            <Box
              sx={{
                height: 200,
              }}
            >
              <img src="concept-image1.png" alt="" />
            </Box>
            <Box
              sx={{
                height: 100,
                backgroundColor: "black",
              }}
            >
              <h5 className={styles.textwhite}>POの企画書文書</h5>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box
              sx={{
                height: 25,
              }}
            >
              <h3 className={styles.textblack}>何か決断するとき</h3>
            </Box>
            <Box
              sx={{
                height: 100,
                backgroundColor: "black",
              }}
            >
              <h5 className={styles.textwhite}>POの企画書文書</h5>
            </Box>
            <Box
              sx={{
                height: 400,
              }}
            >
              <img src="concept-image2.png" alt="" />
            </Box>
          </SwiperSlide>{" "}
          <SwiperSlide>
            <Grid container spacing={1}>
              <Grid item xs={12} alignItems="center">
                <Paper elevation={0} className={styles.paperwhite}>
                  <Typography align="center" variant="h4">
                    モノでもコトでも
                  </Typography>
                </Paper>
              </Grid>
              <Grid item xs={12} alignItems="center">
                <Box
                  sx={{
                    // height: 100,
                    backgroundColor: "black",
                    // padding: 30px,
                  }}
                  className={styles.boxblack}
                >
                  {/* <Paper elevation={0} className={styles.paperblack}> */}
                  <Typography
                    align="left"
                    variant="body1"
                    className={styles.textwhite}
                  >
                    {/* <div> */}
                    現在多くあるのが、商品購買やオークションなど「モノ」のサイト、その他、出会い系、イベントなど「コト」のサイトそれぞれ専門性に特化しています。
                  </Typography>
                  <Typography
                    align="left"
                    variant="body1"
                    className={styles.textwhite}
                  >
                    {/* </div>
                  <div> */}
                    そこで、「コト」「モノ」にとらわれず全てのものを比較でき、個人的に調査比較が簡単にできるサイトがあれば決断の礎になるのではないかと考えます。
                  </Typography>
                  <Typography
                    align="left"
                    variant="body1"
                    className={styles.textwhite}
                  >
                    {/* </div> */}
                    {/* <div>知識欲、決断力を満たしてくれる</div>
                  <div>それが、白黒サイトです。</div> */}
                    知識欲、決断力を満たしてくれる{" "}
                  </Typography>
                  <Typography
                    align="left"
                    variant="body1"
                    className={styles.textwhite}
                  >
                    それが、白黒サイトです。
                  </Typography>
                  {/* </Paper> */}
                </Box>
              </Grid>
              <Grid item xs={12} alignItems="center">
                <Paper elevation={0} className={styles.paperwhitecenter}>
                  <img
                    src="concept-image3.png"
                    alt=""
                    className={styles.image}
                  />
                </Paper>
              </Grid>
            </Grid>
          </SwiperSlide>{" "}
          <SwiperSlide>
            <Box
              sx={{
                height: 25,
              }}
            >
              <h3 className={styles.textblack}>サイトイメージ</h3>
            </Box>
            {/* <Box
            sx={{
              height: 100,
              backgroundColor: "black",
            }}
          >
            <h5 className={styles.textwhite}>POの企画書文書</h5>
          </Box>
          <Box
            sx={{
              height: 300,
            }}
          >
            <img src="concept-image3.png" alt="" />
          </Box> */}
          </SwiperSlide>{" "}
        </Swiper>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://unremoted.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by unremote.com
        </a>
      </footer>
    </div>
  );
};

export default Home;
